project_id = "mediconnect"

[functions.ai]
verify_jwt = true

[functions.admin-ai]
verify_jwt = true

[functions.manager-search-assistant]
verify_jwt = true

[functions.medication-library]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.process-appointment-sms-reminders]
verify_jwt = false
