import type { Medication, MedicationInteraction } from '../../types';

const INTERACTIONS: MedicationInteraction[] = [
  {
    id: 'int-losartana-metformina',
    medicationAId: 'losartana',
    medicationBId: 'metformina',
    medicationAName: 'Losartana',
    medicationBName: 'Metformina',
    severity: 'leve',
    description: 'Associação comum em pacientes diabéticos hipertensos. Monitorar função renal e potássio sérico.',
    clinicalManagement: 'Avaliar creatinina e potássio periodicamente.',
  },
  {
    id: 'int-losartana-amoxicilina',
    medicationAId: 'losartana',
    medicationBId: 'amoxicilina',
    medicationAName: 'Losartana',
    medicationBName: 'Amoxicilina',
    severity: 'leve',
    description: 'Interação clínica geralmente não significativa em curto prazo.',
  },
  {
    id: 'int-metformina-amoxicilina',
    medicationAId: 'metformina',
    medicationBId: 'amoxicilina',
    medicationAName: 'Metformina',
    medicationBName: 'Amoxicilina',
    severity: 'leve',
    description: 'Sem interação farmacodinâmica relevante documentada de rotina.',
  },
  {
    id: 'int-sinvastatina-amoxicilina',
    medicationAId: 'sinvastatina',
    medicationBId: 'amoxicilina',
    medicationAName: 'Sinvastatina',
    medicationBName: 'Amoxicilina',
    severity: 'moderada',
    description: 'Macrolídeos e alguns antibióticos podem elevar níveis de estatinas; amoxicilina costuma ter risco menor, mas monitorar miopatia.',
    clinicalManagement: 'Orientar paciente sobre mialgia ou fraqueza muscular.',
  },
  {
    id: 'int-sinvastatina-metformina',
    medicationAId: 'sinvastatina',
    medicationBId: 'metformina',
    medicationAName: 'Sinvastatina',
    medicationBName: 'Metformina',
    severity: 'leve',
    description: 'Combinação frequente em síndrome metabólica. Sem contraindicação absoluta.',
  },
  {
    id: 'int-sinvastatina-losartana',
    medicationAId: 'sinvastatina',
    medicationBId: 'losartana',
    medicationAName: 'Sinvastatina',
    medicationBName: 'Losartana',
    severity: 'leve',
    description: 'Associação usual em pacientes de risco cardiovascular.',
  },
  {
    id: 'int-dipirona-losartana',
    medicationAId: 'dipirona',
    medicationBId: 'losartana',
    medicationAName: 'Dipirona',
    medicationBName: 'Losartana',
    severity: 'leve',
    description: 'Uso concomitante comum; atenção a reações de hipersensibilidade individual.',
  },
  {
    id: 'int-ozempic-metformina',
    medicationAId: 'ozempic',
    medicationBId: 'metformina',
    medicationAName: 'Ozempic (semaglutida)',
    medicationBName: 'Metformina',
    severity: 'moderada',
    description: 'Combinação indicada em diabetes tipo 2, com risco aumentado de hipoglicemia se associada a secretagogos.',
    clinicalManagement: 'Monitorar glicemia e sintomas de hipoglicemia.',
  },
];

export const MEDICATIONS_CATALOG: Medication[] = [
  {
    id: 'dipirona',
    name: 'Dipirona',
    activeIngredient: 'Metamizol sódico',
    commercialNames: ['Novalgina', 'Anador', 'Dorflex (associação)'],
    therapeuticClass: 'Analgésico e antipirético',
    category: 'Anti-inflamatório não esteroidal (AINES-like)',
    presentations: ['500 mg comprimido', '1 g comprimido', '500 mg/mL gotas', '500 mg/mL solução injetável'],
    manufacturers: ['Sanofi', 'Medley', 'EMS'],
    summary: 'Derivado pirazolônico com ação analgésica e antipirética. Amplamente utilizado no Brasil para dor e febre, com atenção a reações de hipersensibilidade.',
    dosages: [
      { population: 'adultos', usualDose: '500 mg a 1 g', frequency: 'A cada 6–8 h, se necessário', maxDose: '4 g/dia', notes: 'Preferir menor dose eficaz.' },
      { population: 'pediatrico', usualDose: '10–15 mg/kg/dose', frequency: 'A cada 6–8 h', maxDose: 'Conforme peso e formulação', notes: 'Usar gotas ou suspensão pediátrica.' },
      { population: 'idosos', usualDose: '500 mg', frequency: 'A cada 8 h', maxDose: '2 g/dia', notes: 'Ajustar conforme função renal e risco de queda.' },
      { population: 'gestantes', usualDose: 'Evitar, especialmente no 3º trimestre', frequency: '—', maxDose: '—', notes: 'Usar somente se benefício superar risco, conforme protocolo.' },
    ],
    contraindications: {
      absolute: ['Hipersensibilidade conhecida a pirazolonas', 'Porfiria aguda', 'Deficiência de G6PD (relativa a reações hemolíticas)'],
      relative: ['Asma ou urticária induzida por AINES', 'Insuficiência hepática ou renal grave'],
      warnings: ['Risco de agranulocitose (raro)', 'Reações cutâneas graves', 'Não associar a outros analgésicos sem orientação'],
    },
    interactions: INTERACTIONS.filter(i => i.medicationAId === 'dipirona' || i.medicationBId === 'dipirona'),
    source: 'local',
  },
  {
    id: 'amoxicilina',
    name: 'Amoxicilina',
    activeIngredient: 'Amoxicilina',
    commercialNames: ['Amoxil', 'Novamox', 'Clavulin (com clavulanato)'],
    therapeuticClass: 'Antibiótico beta-lactâmico (penicilina)',
    category: 'Antimicrobiano',
    presentations: ['500 mg cápsula', '875 mg comprimido', '250 mg/5 mL suspensão', '500 mg + 125 mg (com clavulanato)'],
    manufacturers: ['GSK', 'Sandoz', 'Eurofarma'],
    summary: 'Penicilina de amplo espectro indicada para infecções bacterianas suscetíveis. Avaliar história de alergia a penicilinas antes da prescrição.',
    dosages: [
      { population: 'adultos', usualDose: '500 mg a 875 mg', frequency: 'A cada 8–12 h', maxDose: '3 g/dia (monoterapia usual)', notes: 'Completar ciclo prescrito.' },
      { population: 'pediatrico', usualDose: '40–45 mg/kg/dia', frequency: 'Dividido a cada 8–12 h', maxDose: 'Conforme peso', notes: 'Suspensão pediátrica preferencial.' },
      { population: 'idosos', usualDose: '500 mg', frequency: 'A cada 12 h', maxDose: 'Ajustar se ClCr < 30 mL/min', notes: 'Monitorar função renal.' },
      { population: 'gestantes', usualDose: '500 mg', frequency: 'A cada 8 h', maxDose: 'Conforme indicação infecciosa', notes: 'Categoria B; usar se indicado clinicamente.' },
    ],
    contraindications: {
      absolute: ['Alergia documentada a penicilinas ou cefalosporinas (reactividade cruzada possível)'],
      relative: ['Mononucleose infecciosa (risco de rash)', 'Insuficiência renal moderada a grave'],
      warnings: ['Colite associada a Clostridioides difficile', 'Reações anafiláticas', 'Uso racional para evitar resistência'],
    },
    interactions: INTERACTIONS.filter(i => i.medicationAId === 'amoxicilina' || i.medicationBId === 'amoxicilina'),
    source: 'local',
  },
  {
    id: 'losartana',
    name: 'Losartana',
    activeIngredient: 'Losartana potássica',
    commercialNames: ['Cozaar', 'Aradois', 'Corus'],
    therapeuticClass: 'Antagonista do receptor de angiotensina II (BRA)',
    category: 'Anti-hipertensivo',
    presentations: ['25 mg comprimido', '50 mg comprimido', '100 mg comprimido'],
    manufacturers: ['MSD', 'EMS', 'Medley'],
    summary: 'BRA utilizado no tratamento de hipertensão arterial e nefroproteção em pacientes selecionados. Monitorar função renal e potássio.',
    dosages: [
      { population: 'adultos', usualDose: '50 mg', frequency: '1x/dia', maxDose: '100 mg/dia', notes: 'Pode iniciar com 25 mg em depleção volêmica.' },
      { population: 'pediatrico', usualDose: '0,7 mg/kg/dia', frequency: '1x/dia (HTA pediátrica)', maxDose: '50 mg/dia', notes: 'Indicação e posologia conforme especialista.' },
      { population: 'idosos', usualDose: '25–50 mg', frequency: '1x/dia', maxDose: '100 mg/dia', notes: 'Iniciar com doses menores.' },
      { population: 'gestantes', usualDose: 'Contraindicado', frequency: '—', maxDose: '—', notes: 'Evitar no 2º e 3º trimestres (fetotoxicidade).' },
    ],
    contraindications: {
      absolute: ['Gravidez (2º/3º trimestres)', 'Hipersensibilidade à losartana', 'Uso concomitante com aliskireno em diabéticos'],
      relative: ['Estenose bilateral de artéria renal', 'Hipercalemia', 'Insuficiência hepática grave'],
      warnings: ['Hipotensão sintomática na descontinuação de diuréticos', 'Monitorar creatinina e potássio', 'Tosse menos frequente que IECA'],
    },
    interactions: INTERACTIONS.filter(i => i.medicationAId === 'losartana' || i.medicationBId === 'losartana'),
    source: 'local',
  },
  {
    id: 'metformina',
    name: 'Metformina',
    activeIngredient: 'Cloridrato de metformina',
    commercialNames: ['Glifage', 'Dimefor', 'Metformina XR'],
    therapeuticClass: 'Biguanida antidiabética',
    category: 'Antidiabético oral',
    presentations: ['500 mg comprimido', '850 mg comprimido', '500 mg XR', '750 mg XR'],
    manufacturers: ['Merck', 'EMS', 'Libbs'],
    summary: 'Primeira linha no diabetes tipo 2, com benefício metabólico e baixo risco de hipoglicemia isolada. Contraindicada em insuficiência renal avançada.',
    dosages: [
      { population: 'adultos', usualDose: '500–850 mg', frequency: '2–3x/dia ou XR 1–2x/dia', maxDose: '2.550 mg/dia (IR) ou 2 g/dia (XR)', notes: 'Titular gradualmente para tolerância GI.' },
      { population: 'pediatrico', usualDose: '500 mg', frequency: '2x/dia (≥10 anos, DM2)', maxDose: '2 g/dia', notes: 'Indicação pediátrica específica.' },
      { population: 'idosos', usualDose: '500 mg', frequency: '1–2x/dia', maxDose: 'Ajustar por ClCr', notes: 'Suspender temporariamente em contraste iodado ou desidratação.' },
      { population: 'gestantes', usualDose: 'Conforme endocrinologia', frequency: 'Individualizado', maxDose: '—', notes: 'Insulina preferencial; metformina em casos selecionados.' },
    ],
    contraindications: {
      absolute: ['ClCr < 30 mL/min (ou eGFR muito reduzido)', 'Acidose metabólica', 'Insuficiência hepática grave', 'Descompensação aguda (sepse, choque)'],
      relative: ['Uso de contraste iodado (pausar conforme protocolo)', 'Insuficiência cardíaca instável', 'Etilismo excessivo'],
      warnings: ['Risco de acidose lática (raro)', 'Distúrbios gastrointestinais', 'Deficiência de B12 em uso prolongado'],
    },
    interactions: INTERACTIONS.filter(i => i.medicationAId === 'metformina' || i.medicationBId === 'metformina'),
    source: 'local',
  },
  {
    id: 'ozempic',
    name: 'Ozempic',
    activeIngredient: 'Semaglutida',
    commercialNames: ['Ozempic', 'Rybelsus (oral)', 'Wegovy (obesidade)'],
    therapeuticClass: 'Agonista do receptor GLP-1',
    category: 'Antidiabético injetável',
    presentations: ['0,25 mg/dose caneta', '0,5 mg/dose caneta', '1 mg/dose caneta', '2 mg/dose caneta'],
    manufacturers: ['Novo Nordisk'],
    summary: 'Semaglutida subcutânea semanal para diabetes tipo 2, com efeito glicêmico e redução de peso. Iniciar com titulação gradual.',
    dosages: [
      { population: 'adultos', usualDose: '0,25 mg (início) → 0,5–1 mg', frequency: '1x/semana SC', maxDose: '2 mg/semana', notes: 'Titular após 4 semanas conforme resposta.' },
      { population: 'pediatrico', usualDose: 'Não indicado rotineiramente', frequency: '—', maxDose: '—', notes: 'Ver aprovações pediátricas específicas.' },
      { population: 'idosos', usualDose: '0,25–0,5 mg', frequency: '1x/semana', maxDose: '1 mg/semana', notes: 'Monitorar tolerância GI e peso.' },
      { population: 'gestantes', usualDose: 'Evitar', frequency: '—', maxDose: '—', notes: 'Dados limitados; preferir insulina.' },
    ],
    contraindications: {
      absolute: ['História pessoal ou familiar de carcinoma medular de tireoide (MEN2)', 'Pancreatite aguda prévia relacionada a GLP-1'],
      relative: ['Retinopatia diabética proliferativa não tratada', 'Doença renal avançada'],
      warnings: ['Náusea, vômito, constipação', 'Risco de pancreatite', 'Ajustar outros antidiabéticos ao titular'],
    },
    interactions: INTERACTIONS.filter(i => i.medicationAId === 'ozempic' || i.medicationBId === 'ozempic'),
    source: 'local',
  },
  {
    id: 'sinvastatina',
    name: 'Sinvastatina',
    activeIngredient: 'Sinvastatina',
    commercialNames: ['Zocor', 'Sinvalip', 'Vast'],
    therapeuticClass: 'Estatinas (inibidor da HMG-CoA redutase)',
    category: 'Hipolipemiante',
    presentations: ['10 mg comprimido', '20 mg comprimido', '40 mg comprimido'],
    manufacturers: ['MSD', 'EMS', 'Aché'],
    summary: 'Estatinas reduzem LDL-colesterol e risco cardiovascular. Evitar doses altas com inibidores potentes de CYP3A4.',
    dosages: [
      { population: 'adultos', usualDose: '10–20 mg', frequency: '1x/dia à noite', maxDose: '40 mg/dia (80 mg reservado)', notes: 'Monitorar enzimas hepáticas e CK se sintomas.' },
      { population: 'pediatrico', usualDose: '10 mg', frequency: '1x/dia (dislipidemia familiar)', maxDose: '40 mg/dia', notes: 'Indicação específica em adolescentes.' },
      { population: 'idosos', usualDose: '10 mg', frequency: '1x/dia', maxDose: '20–40 mg/dia', notes: 'Maior risco de miopatia.' },
      { population: 'gestantes', usualDose: 'Contraindicado', frequency: '—', maxDose: '—', notes: 'Interromper estatinas na gestação.' },
    ],
    contraindications: {
      absolute: ['Gravidez e lactação', 'Doença hepática ativa', 'Hipersensibilidade'],
      relative: ['Uso concomitante de gemfibrozila ou inibidores potentes de CYP3A4', 'Miastenia gravis'],
      warnings: ['Miopatia e rabdomiólise', 'Elevação de transaminases', 'Interação com suco de grapefruit em altas doses'],
    },
    interactions: INTERACTIONS.filter(i => i.medicationAId === 'sinvastatina' || i.medicationBId === 'sinvastatina'),
    source: 'local',
  },
];

export const MEDICATION_SEARCH_EXAMPLES = ['Dipirona', 'Amoxicilina', 'Losartana', 'Metformina', 'Ozempic'] as const;

export const MEDICATION_LEGAL_DISCLAIMER =
  'As informações apresentadas possuem caráter exclusivamente informativo e não substituem avaliação clínica, protocolos institucionais ou julgamento médico.';

export const MEDICATION_SEARCH_HISTORY_KEY = 'mc_medication_search_history';
export const MEDICATION_SEARCH_HISTORY_MAX = 10;
